"use client";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import Slider from "@/components/component/Slider";
import { useRef, useState } from "react";
import Loader from "../ui/AnalyserLoader";
import { AnalyzeAts } from "../api/api";
import pdfToText from "react-pdftotext";
import { usePathname, useRouter } from "next/navigation";
import { toast } from "react-toastify";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import Lottie from "lottie-react";
import animation from "@/public/animations/NonAtsLoaderAnimation.json";
import { GetTokens, RemoveTokens } from "../actions";
import { useUserStore } from "../store/UserStore";
import NewResumeHeader from "../Layout/NewResumeHeader";
import WorkTogether from "@/components/component/WorkTogether";
import Header from "../Layout/Header";
import Footer from "../Layout/Footer";
import { ResumeHeader } from "../Layout/ResumeHeader";
import ServicesPopUp from "@/components/component/ServicesPopUp";
import AccordionItem from "@/components/component/AccordionItem";
import parse from "html-react-parser";
const faqData = [
  {
    id: 1,
    ques: "What is unique about Genies Career Hub’s CV Optimiser?",
    ans: `
      This CV Optimiser thoroughly analyses your resume with AI and provides you feedback with the ATS score. This feedback contains the clarity, relevance, and content of your resume with a score and suggestions to improve the ATS of your resume. Following these insights, you can increase your score and get better and more opportunities.
    `,
  },
  {
    id: 2,
    ques: "How does this CV checker help in increasing the ATS score?",
    ans: `
      Genies Career Hub has the feature of analysing your CV by running it through an optimisation. After analysing, it gives you the feedback with a score in three steps:
      <ul>
        <li>Clarity</li>
        <li>Relevance</li>
        <li>Content</li>
      </ul>
      Follow the suggestions given below each of these to get a better score and get the best opportunities.
    `,
  },
  {
    id: 3,
    ques: "How can I optimise my CV without having an enhanced CV?",
    ans: `
     Follow the following six simple steps:
     <ul>
       <li>Go to the CV Studio page to create an enhanced CV.</li>
       <li>Fill in the required details. You can get your profile description generated by AI if you want and fill in all the details till the end.</li>
       <li>Choose a template of your choice, and choose your desired color.</li>
       <li>Download the CV.</li>
       <li>Go to Optimise CV, upload your CV, and get it analysed.</li>
       <li>Follow the feedback suggestions in case of a low ATS score and re-assess your enhanced resume.</li>
     </ul>
    `,
  },
];

export default function DashboardIdea() {
  const [open, setOpen] = useState(false);
  const pathname = usePathname();
  console.log("pathname::", pathname);
  const [isAnalysing, setIsAnalysing] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const router = useRouter();
  const { userdata } = useUserStore((state) => state.userState);
  const logoutUser = useUserStore((state) => state.logoutUser);
  const updateRedirectPricingRoute = useUserStore(
    (state) => state.updateRedirectPricingRoute
  );
  const [isServiceDialogOpen, setIsServiceDialogOpen] = useState(false);
  const isCreditScore = true;

  const handlepdfFileChange = async (e) => {
    const { accessToken } = await GetTokens();
    if (!accessToken) {
      toast("Please login to use this template");
      return router.push("/login?redirect=/resume-analyzer");
    }
    let selectedFile = e.target.files[0];
    if (!selectedFile) return;
    if (selectedFile?.type !== "application/pdf")
      return toast.error("Please select a valid PDF file");
    setIsAnalysing(true);
    let reader = new FileReader();
    reader.readAsDataURL(selectedFile);
    reader.onloadend = async () => {
      try {
        const text = await pdfToText(selectedFile);
        if (!text) {
          setIsAnalysing(false);
          setIsDialogOpen(true);
          return;
        }
        localStorage.setItem("newResumeContent", text);
        await getFeedback(text, accessToken.value);
      } catch (error) {
      } finally {
        setIsAnalysing(false);
      }
    };
  };

  const getFeedback = async (message, token) => {
    try {
      const response = await AnalyzeAts(message, token);
      if (response.status === "SUCCESS") {
        router.push(`/analyser/${response.analysisId}`);
      }
    } catch (error) {
      if (error.response.status === 403) {
        if (error.response.data.message === "You have no analyser tokens") {
          if (userdata.subscription.plan.includes("CVSTUDIO")) {
            setIsServiceDialogOpen(true);
          } else {
            toast.info(
              "Please subscribe to Genies Pro Suit to use this service",
              { autoClose: 10000 }
            );
            return router.push("/pricing?scroll=1");
          }
        } else {
          toast.info("You do not have a valid plan.", { autoClose: 10000 });
          return router.push("/pricing?scroll=1");
        }
      } else {
        toast.error("Error while analysing your CV.");
      }
    } finally {
      setIsAnalysing(false);
    }
  };

  const handleDialogClose = () => {
    setIsDialogOpen(false);
  };
  const toggle = (index) => {
    if (open === index) {
      return setOpen(null);
    }
    setOpen(index);
  };

  return (
    <>
      <ResumeHeader />
      <main>
        {/* <Header /> */}
        {isAnalysing && <Loader />}
        <section className="flex min-h-screen flex-col items-center justify-center pt-12 bg-gradient-to-t from-[#bde3f2] to-white">
          <Dialog open={isDialogOpen} onClose={handleDialogClose}>
            <DialogContent
              onClick={handleDialogClose}
              className="w-[90%] sm:w-[450px]"
              showCloseButton={true}
            >
              <DialogTitle>
                <div>
                  <Lottie
                    animationData={animation}
                    loop={true}
                    style={{ height: "300px" }}
                  />
                </div>
                Non ATS friendly resume found
              </DialogTitle>
              <DialogDescription>
                Your resume is not ATS friendly. You should use an ATS-friendly
                resume. This is the main reason you are not getting shortlisted.
              </DialogDescription>
              <div className="flex w-full justify-end">
                <Link href="/resume" className="inline">
                  <Button>View Templates</Button>
                </Link>
              </div>
            </DialogContent>
          </Dialog>
          <div className="flex flex-col max-w-8xl text-center px-8  lg:px-32 pt-16 sm:pt-28">
            <div className=" flex flex-col">
              <h1 className="text-4xl lg:text-7xl font-bold mb-6 lg:mb-10 text-gray-900 lg:px-32">
                An <span className="text-blue-600">Optimised CV</span> goes a
                Long Way
              </h1>
              <p className="text-gray-700 text-sm lg:text-md sm:text-lg lg:px-32">
                Wondering why your CV does not get through the initial rounds of
                selection? Analyse your CV with our AI-based CV Optimiser and
                get industry expertise integrated to create an Application
                Tracking System (ATS) friendly resume and flawless application
                profile that gets passed through ATS CV Checker.
              </p>
              <Dialog open={isServiceDialogOpen}>
                <ServicesPopUp
                  isServiceDialogOpen={isServiceDialogOpen}
                  setIsServiceDialogOpen={setIsServiceDialogOpen}
                  serviceName="Create CV"
                />
              </Dialog>
              <div className="flex justify-center mt-12">
                <label className="flex items-center space-x-4 bg-transparent text-blue rounded-lg uppercase cursor-pointer hover:bg-blue sm:mx-auto">
                  <span className="text-md px-10 py-3 bg-blue-900 hover:bg-blue-600 rounded-md text-white font-semibold">
                    Optimise CV Now
                  </span>
                  <input
                    type="file"
                    className="hidden"
                    accept="application/pdf"
                    onChange={handlepdfFileChange}
                  />
                </label>
              </div>
            </div>
            <div className="mt-10 lg:mt-0 flex justify-center lg:justify-start">
              <Image
                priority
                src="/1enhance.png"
                className="rounded-t-3xl w-full sm:w-1/2 mx-auto h-auto responsive-image"
                alt="@shadcn"
                width={600}
                height={100}
              />
            </div>
          </div>
          {/* ***********************NEW SECTION START *****************/}
          <div id="mainDiv" className="w-full bg-white">
            <section>
              <div className="steps_main_section max-w-7xl mx-auto relative lg:p-0 p-10 ">
                <div className="flex flex-col items-center justify-center text-center px-4 lg:px-20 xl:px-10 2xl:px-10">
                  <h2 className="text-4xl lg:text-5xl font-bold mb-2 text-gray-900 w-full pt-20">
                    One Step Ahead of
                  </h2>
                  <h2 className="text-4xl lg:text-5xl font-bold  w-full pt-1  text-[#2C98CA]">
                    CV Checker
                  </h2>

                  <p className="text-base text-black pt-10 w-[95%] sm:w-[85%] md:w-[85%] lg:w-[85%] xl:w-[85%] 2xl:w-[85%]">
                    Top companies across the globe utilise Applicant Tracking
                    Software to simplify their recruiting processes. It would
                    help if you had a compatible and optimised resume to make it
                    through the cracks of the application tracking process for
                    the job role you are targeting.
                  </p>
                  <p className="text-base text-black pt-10 w-[95%] sm:w-[85%] md:w-[85%] lg:w-[85%] xl:w-[85%] 2xl:w-[85%]">
                    At Genies Career Hub, we have decoded the nuances of the
                    Application Tracking Software to build a CV Optimiser that
                    pre notifies you about potential gaps in your CV. With an
                    ATS optimised CV, you can make it to the top of the selected
                    application piles.
                  </p>
                </div>
              </div>
              <div className="max-w-7xl mx-auto lg:py-10 sm:p-5 p-5">
                <h3 className="text-3xl text-black font-bold py-3">
                  Optimise Your CV in 4 simple steps:
                </h3>
                <div className="flex lg:flex-row flex-col gap-10 my-10">
                  {/* <!-- Div 1 --> */}
                  <div className="arrow-shape flex-1 bg-[#FFFCDC] p-5 text-black ">
                    <h6 className="text-[14px] font-bold text-[#2C98CA]">
                      Step 1
                    </h6>
                    <p>
                      Go to <b>CV Optimiser</b>
                    </p>
                  </div>

                  {/* <!-- Div 2 --> */}
                  <div className="arrow-shape flex-1 bg-[#ECFFE7] p-5 text-black">
                    <h6 className="text-[14px] font-bold text-[#2C98CA]">
                      Step 2
                    </h6>
                    <p>
                      Click on <b>Optimise CV Now</b>. Then{" "}
                      <b>Upload your PDF</b>.
                    </p>
                  </div>

                  {/* <!-- Div 3 --> */}
                  <div className="arrow-shape flex-1 bg-[#CEEFFF] p-5 text-black border border-[#CFD8DC]">
                    <h6 className="text-[14px] font-bold text-[#2C98CA]">
                      Step 3
                    </h6>
                    <p>
                      Click on <b>FIX MY CV</b>, then{" "}
                      <b>Optimise current resume</b>
                    </p>
                  </div>

                  {/* <!-- Div 4 --> */}
                  <div className="arrow-shape flex-1 bg-[#FFD9ED] p-5 text-black">
                    <h6 className="text-[14px] font-bold text-[#2C98CA]">
                      Step 4
                    </h6>
                    <p>
                      Make changes, if any and then download your resume with
                      your favorite template and color.
                    </p>
                  </div>
                </div>
              </div>
              <div className="max-w-7xl mx-auto steps_intro lg:py-0 sm:p-5 p-5">
                <div className="flex lg:flex-row flex-col gap-10 my-10">
                  <div className="lg:w-[70%] w-full steps_content">
                    <h3 className="text-3xl text-black font-bold py-3">
                      What is an ATS Resume?
                    </h3>
                    <p className="text-base py-3">
                      Ever wonder how these recruiters segregate and prioritise
                      CVs for the hiring process? 
                    </p>
                    <p className="text-base py-3">
                      The Applicant Tracking System (ATS) is used by most
                      companies to select CVs. The recruiter enters keywords in
                      the ATS database. This software manages the whole
                      recruitment process by ranking applicants&apos; CVs based
                      on their skills, keywords, and experience. 
                    </p>
                    <p className="text-base py-3">
                      It organises the information of an applicant in a way that
                      makes the recruitment process easy. 
                    </p>
                    <p className="text-base py-3">
                      If your resume meets these criteria, you&apos;re lucky.
                      Genies Creer Hub has mastered this system strategy. We
                      create an ATS-friendly resume that will attract the best
                      recruiters.
                    </p>
                  </div>
                  <div className="lg:w-[30%] w-full h-[350px] image_content bg-[#bae6f7]">
                    <img
                      src="/ATS_Resume.png"
                      alt="icon4"
                      className="w-full h-full p-10 object-contain"
                    />
                  </div>
                </div>

                {/*  */}
                <div className="flex lg:flex-row flex-col gap-10 my-10">
                  <div className="lg:w-[40%] w-full h-[150px] image_content bg-[#bae6f7]">
                    <img
                      src="/ATS_Resume.png"
                      alt="icon4"
                      className="w-full h-full p-10 object-contain"
                    />
                  </div>
                  <div className="lg:w-[60%] w-full steps_content">
                    <h3 className="text-4xl text-black font-bold py-3">
                      Resume format for Applicant Tracking System
                    </h3>
                    <p className="text-sm py-3">
                      For a successful ATS friendly resume, you must fill out
                      the following details individually.
                    </p>
                  </div>
                </div>

                {/*  */}

                <div className="step_1">
                  <div className="flex lg:flex-row flex-col gap-10 my-20 relative lg:p-1 p-5">
                    <div className="lg:w-[60%] w-full steps_content">
                      <h4 className="font-bold text-black text-2xl">Step 1</h4>
                      <h3 className="text-4xl text-black font-bold py-3">
                        BASIC INFORMATION
                      </h3>
                      <p className="text-sm py-3">
                        Please provide the basic details, such as your full
                        name, job title, email address, valid phone number,
                        country, and city.
                      </p>
                    </div>
                    <div className="lg:w-[40%] w-full h-[250px] image_content flex flex-col justify-start items-center">
                      <img
                        src="Artboard_ats.png"
                        alt="icon4"
                        className="object-contain mr-32"
                      />
                      <div className="flex lg:flex-row flex-col justify-center items-center">
                        <img
                          src="ats_basic_information.png"
                          alt="icon4"
                          className="object-contain"
                        />
                      </div>
                    </div>

                    <div className="arrow absolute left-[35%] -bottom-40">
                      <img
                        src="/arrow1.png"
                        alt="arrow"
                        className="w-52 h-52 object-contain lg:block hidden"
                      />
                      <img
                        src="/arrow2.png"
                        alt="arrow"
                        className="w-52 h-52 object-contain lg:hidden block"
                      />
                    </div>
                  </div>
                </div>
                <div className="step_2 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full h-[450px] image_content flex justify-center items-center lg:order-first order-last lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex justify-center items-center">
                        <img
                          src="/profile_update_ats.png"
                          alt="icon4"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                    <div className="lg:w-[50%] w-full steps_content mt-10">
                      <h4 className="font-bold text-black text-2xl">Step 2</h4>
                      <h3 className="text-4xl text-black font-bold py-3">
                        PROFILE UPDATES
                      </h3>

                      <p className="text-sm py-3">
                        Fill in a summary of your experiences, your education,
                        and any skills and achievements you achieved in previous
                        years.
                        <br />
                        This is a step where our unique feature of AI will help
                        you generate a valid and professional profile for your
                        ATS resume. 
                      </p>
                      <p className="text-sm py-3">
                        You will just need to fill in some basic information,
                        such as the job role, a summary, and a few things that
                        will help you generate a proper profile description for
                        your CV.
                      </p>
                    </div>
                  </div>
                  {/* <div className="pro_tips">
                    <div className="pro_image relative">
                      <img src="/pro-tips.png" alt="pro-tips" />
                      <p className="text-red-600 font-bold absolute top-3 left-8 text-xl">
                        Pro Tips !
                      </p>
                    </div>
                    <p className="text-xl px-5">
                      Do you wish to change the font style of the text? Yes, you
                      can! We provide you the choice of changing the font style
                      if you do not like the original one. 
                    </p>
                  </div> */}
                  <div className="arrow absolute left-[35%] -bottom-40">
                    <img
                      src="/arrow2.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain"
                    />
                  </div>
                </div>
                <div className="step_3 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full steps_content mt-10">
                      <h4 className="font-bold text-black text-2xl">Step 3</h4>
                      <h3 className="text-4xl text-black font-bold py-3">
                        EDUCATION 
                      </h3>
                      <p className="text-sm py-3">
                        The next step is to fill in your educational details,
                        where you will state the name of the institutions you
                        have studied at, the degree name, and a brief
                        description of your experience.
                      </p>
                    </div>
                    <div className="lg:w-[50%] w-full h-[450px] image_content flex justify-center items-center lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex justify-center items-center">
                        <img
                          src="/profile_education_ats.png"
                          alt="icon4"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                  </div>
                  {/* <div className="pro_tips">
                    <div className="pro_image relative">
                      <img src="/pro-tips.png" alt="pro-tips" />
                      <p className="text-red-600 font-bold absolute top-3 left-8 text-xl">
                        Pro Tips !
                      </p>
                    </div>
                    <p className="text-xl px-5">
                      You can change the design of the templates anywhere in the
                      process of making your CV. 
                    </p>
                  </div> */}
                  <div className="arrow absolute left-[35%] -bottom-40">
                    <img
                      src="/arrow1.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain lg:block hidden"
                    />
                    <img
                      src="/arrow2.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain lg:hidden block"
                    />
                  </div>
                </div>
                <div className="step_4 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full h-[450px] image_content flex justify-center items-center lg:order-first order-last lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex justify-center items-center">
                        <img
                          src="/profile_experience_ats.png"
                          alt="icon4"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                    <div className="lg:w-[50%] w-full steps_content mt-16">
                      <h4 className="font-bold text-black text-2xl">Step 4</h4>
                      <h3 className="text-4xl text-black font-bold py-3">
                        EXPERIENCE 
                      </h3>
                      <p className="text-base py-3">
                        The next step asks about your experience over the years.
                        Fill in specific information like the job title, the
                        employer, and a brief description of the experience.
                      </p>
                    </div>
                  </div>
                  {/* <div className="pro_tips">
                    <div className="pro_image relative">
                      <img src="/pro-tips.png" alt="pro-tips" />
                      <p className="text-red-600 font-bold absolute top-3 left-8 text-xl">
                        Pro Tips !
                      </p>
                    </div>
                    <p className="text-xl px-5">
                      Do you wish to change the shades other than the colors
                      provided? Go ahead and click on the selected color, change
                      the shade by doodling around, and set it 
                    </p>
                  </div> */}
                  <div className="arrow absolute left-[35%] -bottom-40">
                    <img
                      src="/arrow2.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain"
                    />
                  </div>
                </div>
                <div className="step_5 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full steps_content mt-16">
                      <h4 className="font-bold text-black text-2xl">Step 5</h4>
                      <h3 className="text-4xl text-black font-bold py-3">
                        PROJECTS, SKILLS AND HOBBIES
                      </h3>
                      <p className="text-base py-3">
                        projects, skills, and hobbies you have done and even
                        describe them in the description. 
                      </p>
                      <p className="text-base py-3">
                        These skills inform the employer about extracurriculars
                        other than your job role, so fill it cautiously.
                      </p>
                    </div>
                    <div className="lg:w-[50%] w-full h-[450px] image_content flex justify-center items-center lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex justify-center items-center">
                        <img
                          src="/profile_skills_hobbies.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                  </div>
                  {/* <div className="pro_tips">
                <div className="pro_image relative">
                  <img src="/pro-tips.png" alt="pro-tips" />
                  <p className="text-red-600 font-bold absolute top-3 left-8 text-xl">
                    Pro Tips !
                  </p>
                </div>
                <p className="text-xl px-5">
                  Do you wish to change the shades other than the colors
                  provided? Go ahead and click on the selected color, change the
                  shade by doodling around, and set it 
                </p>
              </div> */}
                  <div className="arrow absolute left-[35%] -bottom-20">
                    <img
                      src="/arrow1.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain lg:block hidden"
                    />
                    <img
                      src="/arrow2.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain lg:hidden block"
                    />
                  </div>
                </div>
                <div className="step_6 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full h-[450px] image_content flex justify-center items-center lg:order-first order-last lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex flex-col gap-10 justify-start items-center mt-10">
                        <img
                          src="/profile_awards_certificates_language.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                    <div className="lg:w-[50%] w-full steps_content">
                      <h4 className="font-bold text-black text-2xl">Step 6</h4>
                      <h3 className="text-4xl text-black font-bold py-3">
                        AWARDS, CERTIFICATES AND LANGUAGE
                      </h3>
                      <p className="text-base py-3">
                        If you have received any awards or certificates
                        previously, write them here.
                      </p>
                      <p className="text-base py-3">
                        If you know other languages, do mention them. This helps
                        and increases your chances of getting better
                        opportunities.
                      </p>
                    </div>
                  </div>
                  {/* <div className="arrow absolute left-[35%] -bottom-40">
                    <img
                      src="/arrow2.png"
                      alt="arrow"
                      className="w-52 h-52 object-contain"
                    />
                  </div> */}
                </div>

                <div className="step_7 w-[80%]">
                  <h3 className="text-4xl text-black font-bold py-3">
                    Your ATS Resume Decoded 
                  </h3>
                  <p className="text-base py-3">
                    Our enhanced CV maker is a tool that transforms your
                    existing resume into an Application Tracking System Resume.
                    Genies Career Hub provides you with a transformation in a
                    resume ATS format by giving you an ATS score. This score
                    will help the resume get in a higher rank and will be placed
                    above other people&apos;s CVs
                  </p>
                  <p className="text-base py-3">
                    Analyse your ATS resume with 3-level optimisation.
                  </p>
                  <p className="text-base py-3">
                    Optimise your resume format Clarity, Relevance,  and Content
                    with AI.
                  </p>
                </div>
                {/*  */}
                <div className="max-w-7xl mx-auto lg:py-10 sm:p-5 p-5">
                  <h3 className="text-3xl text-black font-bold py-3">
                    Our 3-level optimisation checker-
                  </h3>
                  <div className="flex lg:flex-row flex-col gap-10 my-10">
                    {/* <!-- Div 1 --> */}
                    <div className="arrow-shape flex-1 bg-[#D8DAFF] p-5 text-black ">
                      <h6 className="text-[18px] font-bold text-[#2C98CA]">
                        1. CLARITY
                      </h6>
                      <p>
                        Gives you clarity of your resume in a clear and concise
                        manner
                      </p>
                    </div>

                    {/* <!-- Div 2 --> */}
                    <div className="arrow-shape flex-1 bg-[#FFCDCD] p-5 text-black">
                      <h6 className="text-[18px] font-bold text-[#2C98CA]">
                        2. RELEVANCE
                      </h6>
                      <p>
                        Informs you about the relevance of your resume to the
                        job title.
                      </p>
                    </div>

                    {/* <!-- Div 3 --> */}
                    <div className="arrow-shape flex-1 bg-[#D5FED9] p-5 text-black border border-[#CFD8DC]">
                      <h6 className="text-[18px] font-bold text-[#2C98CA]">
                        3. CONTENT
                      </h6>
                      <p>
                        Gives you an idea if your content contains of the
                        relevant information to the job profile.
                      </p>
                    </div>
                  </div>
                </div>
                {/*  */}
                {/*  */}
                <div className="pro_tips">
                  <div className="pro_image relative">
                    <img src="/pro-tips.png" alt="pro-tips" />
                    <p className="text-red-600 font-bold absolute top-3 left-8 text-xl">
                      Pro Tips !
                    </p>
                  </div>
                  <p className="text-xl px-5">
                    Wish you had a better ATS System Friendly Score! Do it right
                    away. Our Optimiser results show your score and suggestions
                    in resume ATS format. Follow the tips, and you can increase
                    your ATS Resume score.
                  </p>
                </div>
                {/*  */}
                {/* step-1 */}
                <div className="step_6 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full steps_content order-last lg:order-first ">
                      {/* <h4 className="font-bold text-black text-2xl">Step 6</h4> */}
                      <h3 className="text-4xl text-black font-bold py-3">
                        How to use our CV checker?
                      </h3>

                      <p className="text-base py-3 font-bold">
                        1. Go to CV Studio to Optimise Your CV and Click
                        Optimise CV Now. Upload Your Resume in PDF Form.
                      </p>
                      <p className="text-base py-3">
                        Need an enhanced resume? You can go to the CV Creator
                        and prepare your ATS Resume in 4 easy steps. 
                      </p>
                    </div>
                    <div className="lg:w-[50%] w-full h-[250px] image_content flex justify-center items-center  lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex flex-col gap-10 justify-start items-center mt-0">
                        <img
                          src="/profile_ats_am_optimised_cv.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                {/*  */}
                {/* step-2 */}
                <div className="step_6 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full steps_content">
                      <p className="text-base py-3 font-bold">
                        2. Check the Resume Format ATS Score in the CV Insights
                      </p>
                      <p className="text-base py-3">
                        You must upload your resume in Optimise CV Now and let
                        the AI analyse the score. Your ATS score will appear at
                        the top. Our CV Optimiser will also provide you with
                        feedback based on the clarity, relevance, and quality of
                        the content.
                      </p>
                      <p className="text-base py-3">
                        Our optimiser gives decent feedback and suggestions on
                        how to improve the score. It will guide you by
                        suggesting essential points to enhance resume.
                      </p>
                    </div>
                    <div className="lg:w-[50%] w-full h-[250px] image_content flex justify-center items-center  lg:bg-transparent bg-[#d3e9f4] order-last lg:order-first">
                      <div className="flex flex-col gap-10 justify-start items-center mt-0">
                        <img
                          src="/profile_cv_insights.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                {/*  */}
                {/*step-3  */}
                <div className="step_6 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full steps_content order-last lg:order-first ">
                      <p className="text-base py-3 font-bold">
                        3. Review Your ATS Resume Feedback or Suggestions and
                        Start Making Corrections
                      </p>
                      <p className="text-base py-3">
                        Our CV Optimiser will provide recommendations to improve
                        your enhanced CV, increasing your chances of getting
                        hired. 
                      </p>
                      <p className="text-base py-3">
                        Go thoroughly through the issues in recommendations, and
                        accordingly make changes in your ATS resume.
                      </p>
                    </div>
                    <div className="lg:w-[50%] w-full h-[250px] image_content flex justify-center items-center  lg:bg-transparent bg-[#d3e9f4]">
                      <div className="flex flex-col sm:flex-row md:flex-row lg:flex-row xl:flex-row 2xl:flex-row  gap-5 justify-start items-center mt-0">
                        <img
                          src="/profile_clarity_ats.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                        <img
                          src="/profile_relevance_ats.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                        <img
                          src="/profile_content_ats.png"
                          alt="icon5"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                {/*  */}
                {/*step-4  */}
                <div className="step_6 relative">
                  <div className="flex lg:flex-row flex-col gap-10 mt-20 lg:p-1 p-5">
                    <div className="lg:w-[50%] w-full steps_content order-last lg:order-first ">
                      <p className="text-base py-3 font-bold">
                        4. Click on Fix My CV to Make Changes Manually.
                      </p>
                      <p className="text-base py-3">
                        Make changes to your ATS-friendly resume by following
                        the recommendations that will make the CV an enhanced
                        CV, and achieve a more significant ATS score.  
                      </p>
                      <p className="text-base py-3">
                        Take an overview of the details, the content, the
                        templates, and the color at the end. Make changes
                        according to your preferences, and you will be able to
                        download the improvised resume quickly.
                      </p>
                    </div>
                    <div className="lg:w-[50%] w-full h-[250px] image_content flex justify-center items-center  lg:bg-transparent bg-[#d3e9f4]"></div>
                  </div>
                </div>
                {/*  */}
                {/*  */}
                <div className="pro_tips">
                  <div className="pro_image relative">
                    <img src="/pro-tips.png" alt="pro-tips" />
                    <p className="text-red-600 font-bold absolute top-3 left-8 text-xl">
                      Pro Tips !
                    </p>
                  </div>
                  <p className="text-xl px-5">
                    If you wish to recheck your resume for a better score after
                    making the changes once, just upload your improvised CV to
                    our ATS CV checker. Then, make more improvements with
                    suggestions and download the resume. 
                  </p>
                </div>
                {/*  */}

                {/*  */}
                <div className="flex lg:flex-row flex-col gap-10 my-10">
                  <div className="lg:w-[70%] w-full steps_content">
                    <h3 className="text-3xl text-black font-bold py-3">
                      Is our ATS Resume Checker successful in Improving the ATS
                      Score?
                    </h3>
                    <p className="text-base py-3">
                      Yes, Genies Career Hub provides job-seekers with a chance
                      to improve their ATS resume scores. This ATS CV checker
                      analyses your resume with AI and then bifurcates it based
                      on the clarity, relevance, and content of your resume
                      format.  
                    </p>
                    <p className="text-base py-3">
                      After breaking down these into three, our optimiser gives
                      insights into the areas of improvement to increase each of
                      the scores. These insights can be some keywords or
                      specific details similar to your job profile meeting
                      industry standards.
                    </p>
                    <p className="text-base py-3">
                      By following the insights and making changes, you can
                      re-assess your ATS resume score and witness the change in
                      score.
                    </p>
                    <p className="text-base py-3">
                      For a clear picture, we have provided an example of
                      witnessing the score change after following some
                      instructions.
                    </p>
                  </div>
                  <div className="lg:w-[30%] w-full h-[350px] image_content bg-[#bae6f7]">
                    <img
                      src="/ATS_Resume.png"
                      alt="icon4"
                      className="w-full h-full p-10 object-contain"
                    />
                  </div>
                </div>
                {/*  */}
              </div>
            </section>
          </div>
          {/* NEW SECTION END */}
          {/* <div className="w-full mt-10 lg:mt-0">
            <div className="rounded-t-3xl border-t-8 border-blue-500 bg-gradient-to-b from-[#dcecff] to-white">
              <Slider />
            </div>
          </div> */}
        </section>
        <section className="faq py-20">
          <div className="max-w-7xl mx-auto flex lg:flex-row flex-col">
            <div className="faq_image lg:w-[50%] w-full lg:block hidden">
              <div className="image_div w-[400px] h-[400px]">
                <img src="/faq_image.png" alt="faq" className="w-full h-full" />
              </div>
            </div>
            <div className="faq_content lg:w-[50%] w-full lg:p-1 p-5">
              <h2 className="text-3xl text-center text-bold font-semibold my-5">
                Frequently Asked Questions
              </h2>
              {faqData?.map((item, index) => (
                <AccordionItem
                  open={index === open}
                  key={index}
                  ques={item?.ques}
                  ans={parse(item?.ans)}
                  pathname={pathname}
                  toggle={() => toggle(index)}
                />
              ))}
            </div>
          </div>
        </section>
        <WorkTogether />
        <Footer />
      </main>
    </>
  );
}
