/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kEoK0vUpxYX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Image from "next/image"

export default function DashboardIdea() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-gray-100 p-4 ">
      <div className="container max-w-4xl">
        <div className="rounded-lg bg-white p-6 shadow-md ">
          <div className="flex items-center space-x-6">
            <Avatar className="h-20 w-20">
              <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Jared Palmer</h2>
              <p className="text-gray-500 dark:text-gray-400">Frontend Developer</p>
              <div className="flex items-center space-x-4">
                <div className="flex items-center space-x-1">
                  <LocateIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">San Francisco</span>
                </div>
                <div className="flex items-center space-x-1">
                  <LinkIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                  <Link className="text-sm text-gray-500 hover:underline dark:text-gray-400" href="#">
                    jaredpalmer.com
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-8 rounded-lg bg-white p-6 shadow-md ">
          <Tabs className="w-full" defaultValue="personal">
            <TabsList className="mb-4 flex w-full justify-center border-b border-gray-200 dark:border-gray-800">
              <TabsTrigger value="personal">Personal</TabsTrigger>
              <TabsTrigger value="professional">Professional</TabsTrigger>
              <TabsTrigger value="side-projects">Side Projects</TabsTrigger>
            </TabsList>
            <TabsContent value="personal">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Card>
                  <CardHeader>
                    <CardTitle>Personal Project 1</CardTitle>
                    <CardDescription>A personal project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 1"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Personal Project 2</CardTitle>
                    <CardDescription>Another personal project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 2"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Personal Project 3</CardTitle>
                    <CardDescription>A third personal project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 3"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
              </div>
            </TabsContent>
            <TabsContent value="professional">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Card>
                  <CardHeader>
                    <CardTitle>Professional Project 1</CardTitle>
                    <CardDescription>A professional project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 1"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Professional Project 2</CardTitle>
                    <CardDescription>Another professional project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 2"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Professional Project 3</CardTitle>
                    <CardDescription>A third professional project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 3"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
              </div>
            </TabsContent>
            <TabsContent value="side-projects">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Card>
                  <CardHeader>
                    <CardTitle>Side Project 1</CardTitle>
                    <CardDescription>A side project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 1"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Side Project 2</CardTitle>
                    <CardDescription>Another side project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 2"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Side Project 3</CardTitle>
                    <CardDescription>A third side project I worked on.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Image
                      alt="Project 3"
                      className="aspect-video w-full rounded-md object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400}
                    />
                  </CardContent>
                  <CardFooter>
                    <Button variant="link">View Project</Button>
                  </CardFooter>
                </Card>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  )
}

function LinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}


function LocateIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}
